### ISSUE TITLE
Drafting a proposal for a DTS 'Search' feature

### ISSUE THREAD

**Issue by PietroLiuzzo** [distributed-text-services/workshops#11]
# Proponent / Mentor
@PietroLiuzzo 

# Brief Description
It is nice if I can browse a collection. But what about I search first, so that instead of 2000 results I get a more processable shortlist? this would be a specification Hack, drafting a proposal in the form of a PR for an additional `query` parameter in the DTS Collection and Navigation APIs.

# Coding skills needed
I guess to make a contribution to the spec, one needs to understand how the API works, how GitHub works, how markdown works.

# Team members (if applicable)
all welcome! please add your name/user name.

**Comment by jonathanrobie** [comment]
Probably not a good idea to ask a hackathon to draft the specification.   I doubt that we would accept any pull request 'as is', and anyone who wants to be involved in creating a search feature probably needs to understand the discussions we have had previously.

**Comment by PietroLiuzzo** [comment]
Dear @jonathanrobie I do not think that there is any expectation that a PR is accepted "as is". it may be rejected "as is" with a good motivation, it may be discussed and reviewed with many requests for changes, but since DTS is community based, I would assume that contributions from the community would be welcome, and not prevented for lack of previous involvement. If a group at the hackaton does come up with something I would think that others will have a look and constructively interact on the basis of that. If the hack group does not feel ready for a PR, it may become simply an issue, always looking for discussion with others. Perhaps you would like to be part of this hack project from the outset?

**Comment by jonathanrobie** [comment]
Are you familiar with the search/query proposals that we have already
discussed?  I wrote proposals for search and query, we decided not to take
it on in 1.0, the current status is that we are finishing the current batch
of proposals first. If we get another proposal, I imagine it will be put on
hold along with the existing proposals until the group decides it has the
bandwidth to take this new feature on.

I really would like to see search/query in the spec. I just want to avoid a
situation where an outside group is encouraged to develop a proposal,
identifies with it, expects us to accept it, and will be disappointed if we
do not.

**Comment by PietroLiuzzo** [comment]
no, I am not familiar with your proposal. if there is already one, that it simply makes no sense to draft another. it would be nice if you would like to propose an hackathon task to review and comment on your proposal instead, so that perhaps it would on one side help the group and eventually make its way into a new release.
