### ISSUE TITLE
DTS 2 CSV Hack

### ISSUE THREAD

**Issue by laurentmldev** [distributed-text-services/workshops#15]
# Proponent / Mentor
@laurentmldev / MetaindeX Team

# Brief Description
Implement a Python script to walk through DTS contents via API, and storing results as CSV file.
This (those) CSV file(s) would be then available for complementary processing with various tools such as MetaindeX (http://metaindex.fr) for cataloging, exploring and getting statistical analysis.

# Coding skills needed
Python basics.

# Team members (if applicable)
@laurentmldev for core development.
Other members welcome especially as key-users to test/improve the tool and define a global scenario for overall demo.

**Comment by PietroLiuzzo** [comment]
Hi! I was wondering from yesterday is a simple tabular view of the json-ld data would not be the simples way to achieve this?
I have loaded into  https://json-ld.org/playground/ a navigation endpoint page from my DTS implementation https://betamasaheft.eu/api/dts/navigation?id=https://betamasaheft.eu/ESum035 and got a nice csv table https://tinyurl.com/yz2tw6wr among other possible output formats? Just to share! thanks a lot!

**Comment by laurentmldev** [comment]
Yes that is what is more or less plan but with finer grain than global conversion.

Here is the process we plan:
- start from a given point in the DTS hierarchy (we don't always want to retrieve all of it but maybe only a sub-branch)
- walk through all children (collections and resources) from the starting point
- at each level, we extract only "fields declared as interesting in the tool's config". Applying if needed some "transform" via a python function provided by the user if he wants to. That is sometimes useful to normalize some text, remove carriage returns from titles (if we want them in the CSV file) etc.
- build a collections.csv and a resources.csv files out of extracted data
- optionnally retrieve resources TEI files, and convert them to plain text (or even HTML) using Saxon and TEI-XSL if available on running system. This allows us then to compute basic stats such as number of words in the resource for example and add it in generated CSV data.

Retrieving fields contents from JSON towards CSV by the way might be a bit trickier for json 'array' contents. Current approach is to specify explicitly which index to extract (ex: myfield[2])

We'll have some sample config files to show next week I guess so that we can show some parts and get live feedback from the community.

**Comment by AudricWannaz** [comment]
adding myself - AudricWannaz - as team member

**Comment by laurentmldev** [comment]
• **Hack location**: https://github.com/AudricWannaz/DTS2CSV/tree/main/dts2csv
• **Documentation**: https://github.com/AudricWannaz/DTS2CSV/tree/main/dts2csv
• Basic backend works standalone. Dep to Streamlit for GUI and Saxon/TEI-XSL for TEI processing.
• For Anyone who may want to extract contents from DTS API into CSV
